CREATE SEQUENCE  "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE "OSB_RETRY_MESSAGE"
(	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "MESSAGE_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "OWNER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
     "COMPONENT_DN" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
     "GROUP_ID" VARCHAR2(1000 BYTE) NOT NULL ENABLE,
     "RETRY_DATE" TIMESTAMP (6) NOT NULL ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SMSOADV6_SOAINFRA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE_TRG" 
BEFORE INSERT ON OSB_RETRY_MESSAGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OSB_RETRY_MESSAGE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE_TRG" ENABLE;

ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("OWNER_ID" NOT NULL ENABLE);
ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("COMPONENT_DN" NOT NULL ENABLE);
ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("GROUP_ID" NOT NULL ENABLE);
ALTER TABLE "SMSOADV6_SOAINFRA"."OSB_RETRY_MESSAGE" MODIFY ("RETRY_DATE" NOT NULL ENABLE);
